apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  # namespace: my-namespace
data:
  # the URL is nothing else but the name of mongodb service
  # note, mongodb-service not mongodb-deployment
  database_url: mongodb-service