# deployment yaml config
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mongodb-deployment
  labels:
    app:  mongodb
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret      # choose this file
              key: mongo-root-username  # choose this variable
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password

# 3 - below is syntax for new doc start in same yaml file 
# - above is config for deployment and below is config for service 
---

# service yaml config
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017       # this is port for service, on which request should come
      targetPort: 27017 # this is port which pod/container expose
                        # this sould match the containerPort in deploy config
                        # because service forward request from port to targetPort on pod

